# loosely based on https://blog.devgenius.io/automating-installation-of-ha-rke2-kubernetes-cluster-with-ansible-2456cc95d970

  - name: get the token
    shell: cat /var/lib/rancher/rke2/server/node-token
    delegate_to: "{{ groups['controller_one'][0] }}"
    register: TOKEN
    changed_when: False    
    run_once: True

  - name: create directories
    file:
      path: "{{ item }}"
      state: directory
      owner: root
      group: root
      recurse: yes
    loop:
      - /etc/rancher/rke2
      - /var/lib/rancher/rke2/server/manifests

  - name: Creating the config.yaml
    copy:
      dest: "{{ CONFIG_FILE }}"
      content: |
        token: {{ TOKEN.stdout }}
        server: https://{{ hosts_gw }}:9345
    notify: "rke2-agent service restart"

  - name: download rke2.sh
    get_url:
      url: https://get.rke2.io
      dest: /root/rke2.sh
      mode: '0700'

  - name: Installing rke2 agent
    shell: ./rke2.sh
    notify: "rke2-agent service restart"
    environment: 
      INSTALL_RKE2_VERSION: "{{ rke2_version }}"
      INSTALL_RKE2_TYPE: "agent" 

  - name: Starting rke2 agent
    systemd:
      name: rke2-agent
      state: restarted
      enabled: true

